apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: my-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "appdb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
